### ISSUE TITLE
verdaccio添加自定义插件

### ISSUE THREAD

**Issue by whg4** [whg4/notes#16]
# verdaccio添加自定义插件

### 编写插件

如何生成插件模板，可以看[官网教程](https://verdaccio.org/docs/plugin-generator/)

### 安装插件

这里假设我们的插件npm包名为**verdaccio-authgroup**，需要在verdaccio安装的目录下面安装插件，否则启动verdaccio时会报无法识别插件的问题，例如`/nvm/v16.18.1/node_modules/verdaccio`这个目录下面执行下面的命令。

```
npm install verdaccio-authgroup
```

### config.yaml配置

```
web:
  title: Verdaccio
  
auth:
  htpasswd:
    file: ./htpasswd
  # 自定义插件在这里声明，如果你的包名为verdaccio-authgroup，插件名要写成authgroup
  authgroup:
    test: test test-bot # 声明test组的成员

#...

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  'test-package':
  # 这里配置只允许test-bot进行publish，unpublish操作
    access: $all 
    publish: test-bot
    unpublish: test-bot
    proxy: npmjs

```
